RockRoot: ../../..
HeaderFontSize: 10
PortFontSize: 8
PortIconScale: 1.3333
retinaScale: 1.
dbType: Serverless # one of [Serverless, Client, MultiDBClient]
dbPath: database/modkom_db
dbGraph: master
dbAddress: http://localhost:8183