RockRoot: ../../..
HeaderFontSize: 10
PortFontSize: 8
PortIconScale: 1.3333
retinaScale: 1.
dbType: Serverless # one of [Serverless, Client, MultiDBClient]
dbPath: modkom/component_db
dbGraph: graph_test
dbAddress: http://localhost:8183