main_server:
  type: Serverless
  path: database/modkom_db
  graph: master
import_servers:
  - type: Serverless
    path: database/atomic_component_db 
    graph: orogen_tasks
  - type: Serverless
    path: database/backbone_reference_db
    graph: master