main_server:
  type: Serverless
  path: modkom/component_db
import_servers:
  - type: Serverless
    path: database/atomic_component_db
    graph: graph_test
  - type: Client
    url: http://localhost:8183
    graph: graph_production
