main_server:
  type: Serverless
  graph: master
  path: database/backbone_reference_db
  readonly: true
import_servers:
  - name: my_import_server
    type: Serverless
    path: database/atomic_component_db
    graph: orogen_tasks
    readonly: false
