main_server:
  type: Serverless
  path: modkom/component_db
  graph: graph_test
import_servers:
  - type: Serverless
    path: database/atomic_component_db 
    graph: orogen_tasks
  - type: Serverless
    path: database/backbone_reference_db
    graph: master